INSERT INTO [dbo].[Pais]([idPais] ,	[Nombre] )
VALUES ('144','Afganistán'          ),
('114', 'Albania'					 ),
('18','Alemania'					 ),
('98','Algeria'						 ),
('145','Andorra'					 ),
('119','Angola'						 ),
('4','Anguilla'						 ),
('147','Antigua y Barbuda'  		 ),
('207','Antillas Holandesas'  		 ),
('91','Arabia Saudita'				 ),
('5','Argentina'				     ),
('6','Armenia'						 ),
('142','Aruba'						 ),
('1','Australia'					 ),
('2','Austria'						 ),
('3','Azerbaiyán'					 ),
('80','Bahamas'						 ),
('127','Bahrein'					 ),
('149','Bangladesh'					 ),
('128','Barbados'					 ),
('9','Bélgica'						 ),
('8','Belice'						 ),
('151','Benín'						 ),
('10','Bermudas'					 ),
('7','Bielorrusia'					 ),
('123','Bolivia'					 ),
('79','Bosnia y Herzegovina'		 ),
('100','Botsuana'					 ),
('12','Brasil'						 ),
('155','Brunéi'						 ),
('11','Bulgaria'					 ),
('156','Burkina Faso'				 ),
('157','Burundi'					 ),
('152','Bután'						 ),
('159',	'Cabo Verde'				 ),
('158',	'Camboya'					 ),
('31','Camerún'						 ),
('32','Canadá'					     ),
('130',	'Chad'						 ),
('81',	'Chile'						 ),
('35','China'						 ),
('33','Chipre'						 ),
('82','Colombia'					 ),
('164','Comores'					 ),
('23','Egipto'						 ),
('51','El Salvador'					 ),
('93','Emiratos Árabes Unidos'		 ),
('55','Estados Unidos'           	 ),
('24','Israel'						 ),
('29','Italia'						 ),
('132','Jamaica'					 ),
('70','Japón'						 ),
('84','Corea del Norte'				 ),
('69',	'Corea del Sur'				 ),
('168',	'Costa de Marfil'			 ),
('36','Costa Rica'					 ),
('71',	'Croacia'					 ),
('113',	'Cuba'						 ),
('22',	'Dinamarca'		     		 ),
('68','Estonia'						 ),
('90','Filipinas'					 ),
('63','Finlandia'					 ),
('64','Francia'						 )
